### PR TITLE
Lg/default frontend

### PR DESCRIPTION
**Pull request by lsgunnlsgunn**
DRAFT section for the generated web UI.

### CODE REVIEW

**Comment by lsgunnlsgunn** [comment]
Yeah, I was kind of debating about this with myself as well. On the one hand, it is nice to have each tutorial be a standalone subject topic. On the other hand it would be fine to work this into the existing tutorials. I went with this approach to try to focus each tutorial on only one "topic" even though most of the steps are the same/similar. I'll think a little more on this.

**Comment by chenyan-dfinity** [comment]
Yes, I think both ways work fine. My thinking is that now we have two ways to communicate with the canisters: one through CLI canister calls, and one through this web interface. In all the tutorials, we mention how to send a message via CLI, so it's natural to also mention that we have a web interface to do the same thing. This doesn't need to go into all tutorials. Maybe we can just mention this in the more complex tutorials like phonebook, where the input format is more complicated to type textually. In these cases, web interface provides a better way for testing and debugging.

**Comment by lsgunnlsgunn** [comment]
Yes, that's a good idea. I thinkI will add it, then later I might decide to remove the standalone tutorial altogether.

**Comment by chenyan-dfinity** [comment]
Do you think we can postpone the standalone tutorial? I would like to make a stab at this in a later time to go deeper into the web interface, explaining all the UI widgets we are using for different types, and how a frontend developer can use/customize this UI for their web app (This feature is not available yet).

The current tutorial feels a bit redundant with #31, and may give a wrong impression that a simple UI is all we have.

**Comment by lsgunnlsgunn** [comment]
Closing in favor of the included file.https://github.com/dfinity-lab/docs/pull/31

**Pull request closed without merging**
